config/routes.rb
GitMyCurriculum::Application.routes.draw do

  get 'search/uc_search'
  get 'user_root' => 'profile#load'

  authenticated :user do
    root to: 'dashboard#show', as: 'authenticated_root'
  end

  devise_for :users, controllers: { confirmations: 'confirmations', passwords: 'passwords', registrations: 'registrations', sessions: 'sessions' }

  root 'splash#load'

  get 'splash/load'

  get 'profile/edit'
  get 'profile/load'
  get 'dashboard/show'

  resources :curricula do

    member do
      get 'tree/:name' => 'curricula#grab_tree_folder', as: :open_folder
      get 'blob/:name' => 'curricula#grab_file_contents', as: :open_file, :name => /(\w+)(\D+)(\w)/
      get 'fork' => 'curricula#fork', as: :fork
    end

  end

  namespace :curricula do

    get ':id/settings', to: 'settings#show', as: :settings
    post ':id/settings', to: 'settings#show', as: :settings_post

    get 'settings/contributors' => 'settings#update_contributors', as: :contributors
    get 'settings/search' => 'settings#search_results', as: :settings_search

    get ':id/requests/' => 'pull_request#show_requests', as: :requests
    get 'join/:id' => 'pull_request#pull_request', as: :join_request
    get 'merge/:id' => 'pull_request#merge_request', as: :merge
    post 'comment' => 'pull_request#comment', as: :comment

    get ':id/download' => 'exchanges#download', as: :download
    get ':id/upload' => 'exchanges#upload', as: :show_upload
    post ':id/upload' => 'exchanges#upload', as: :post_upload

    get ':id/history' => 'history#show', as: :history
    get ':id/compare/:commit' => 'history#compare', as: :compare
    get ':id/revert/:commit' => 'history#revert', as: :revert

  end

  get 'splash/load'

  get 'subscriptions/subscription'
  post 'subscriptions/subscription' => 'subscriptions#subscription', as: :subscription

  get 'source/show/:id' => 'source#show', as: :source_show
  post 'source/edit' => 'source#edit', as: :source_edit

  get 'featured/show' => 'featured#show', as: :featured_show
  get 'featured/add_featured' => 'featured#add_featured', as: :add_featured
  get 'featured/remove_featured' => 'featured#remove_featured', as: :remove_featured

end

app/models/source.rb
# create_table "sources", force: true do |t|
#   t.integer  "curricula_id", null: false
#   t.integer  "creator_id",   null: false
#   t.string   "author"
#   t.string   "title"
#   t.string   "source_tag"
#   t.datetime "created_at",   null: false
#   t.datetime "updated_at",   null: false
#   t.datetime "written_at"
# end
class Source < ActiveRecord::Base
  belongs_to :curricula
  belongs_to :creator, class_name: 'User'

  class << self
    def grab_sources_for_curriculum(curriculum)
      where('sources.curricula_id = ?', curriculum)
    end
  end
end

app/controllers/source_controller.rb
# shows and adds sources
class SourceController < ApplicationController
  def show
    @curriculum = Curricula.find_by_id(params[:id])
    @sources = Source.grab_sources_for_curriculum @curriculum
  end

  def edit
    @curriculum = Curricula.find_by_id(params[:id])
    @source = Source.new(source_params)
    @source.creator = current_user
    @source.curricula = @curriculum
    if @source.save
      flash[:success] = 'Success'
    else
      flash[:danger] = 'Error! Try submitting again'
    end
    @sources = Source.grab_sources_for_curriculum @curriculum
    respond_to do |format|
      format.js
    end
  end

  private

  def source_params
    params.require(:source).permit(:link, :source_tag)
  end
end

app/views/source/_sources.html.erb
<% unless @sources.blank? %>
  <% @sources.each do |s| %>
    <div class="list-group-item">
      <a class="list-group-item-heading" href=<%= s.link %>><%= s.source_tag %></a>
    </div>
  <% end %>
<% end %>

app/views/source/edit.js.erb
$('#status').html("<%= escape_javascript(render :partial => 'shared/flash_messages') %>");
$('#source-list').html("<%= escape_javascript(render :partial => 'sources') %>");
$('#source_link').val("");
$('#source_source_tag').val("");

app/views/source/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3" title="Add source here">
      <div id="status">
      </div>
      <%= form_for :source, :url => source_edit_path(:id => @curriculum.id), :role => "form", :class => "form", :method => :post, :remote => true do |f| %>
        <div class="form-group">
          <%= f.text_field :link, type:"text", placeholder:"url for source", class:"form-control", :autofocus => true %>
        </div>
        <div class="form-group">
          <%= f.text_field :source_tag, type:"text", placeholder:"tag for source", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "add source", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-info">
        <div class="panel-heading">
          Sources
        </div>
        <div class="list-group" id="source-list">
          <% unless @sources.blank? %>
            <% @sources.each do |s| %>
              <div class="list-group-item">
                <a class="list-group-item-heading" href=<%= s.link %>><%= s.source_tag %></a>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>