config/routes.rb
GitMyCurriculum::Application.routes.draw do

  get 'search/uc_search'
  get 'user_root' => 'profile#load'

  authenticated :user do
    root to: 'dashboard#show', as: 'authenticated_root'
  end

  devise_for :users, controllers: { confirmations: 'confirmations', passwords: 'passwords', registrations: 'registrations', sessions: 'sessions' }

  root 'splash#load'

  get 'splash/load'

  get 'profile/edit'
  get 'profile/load'
  get 'dashboard/show'

  resources :curricula do

    member do
      get 'tree/:name' => 'curricula#grab_tree_folder', as: :open_folder
      get 'blob/:name' => 'curricula#grab_file_contents', as: :open_file, :name => /(\w+)(\D+)(\w)/
      get 'fork' => 'curricula#fork', as: :fork
    end

  end

  namespace :curricula do

    get ':id/settings', to: 'settings#show', as: :settings
    post ':id/settings', to: 'settings#show', as: :settings_post

    get 'settings/contributors' => 'settings#update_contributors', as: :contributors
    get 'settings/search' => 'settings#search_results', as: :settings_search

    get ':id/requests/' => 'pull_request#show_requests', as: :requests
    get 'join/:id' => 'pull_request#pull_request', as: :join_request
    get 'merge/:id' => 'pull_request#merge_request', as: :merge
    post 'comment' => 'pull_request#comment', as: :comment

    get ':id/download' => 'exchanges#download', as: :download
    get ':id/upload' => 'exchanges#upload', as: :show_upload
    post ':id/upload' => 'exchanges#upload', as: :post_upload

    get ':id/history' => 'history#show', as: :history
    get ':id/compare/:commit' => 'history#compare', as: :compare
    get ':id/revert/:commit' => 'history#revert', as: :revert

  end

  get 'splash/load'

  get 'subscriptions/subscription'
  post 'subscriptions/subscription' => 'subscriptions#subscription', as: :subscription

  get 'source/show/:id' => 'source#show', as: :source_show
  post 'source/edit' => 'source#edit', as: :source_edit

  get 'featured/show' => 'featured#show', as: :featured_show
  get 'featured/add_featured' => 'featured#add_featured', as: :add_featured
  get 'featured/remove_featured' => 'featured#remove_featured', as: :remove_featured

end

app/controllers/dashboard_controller.rb
# Controller the dashboard features
class DashboardController < ApplicationController
  include NotificationManager

  # loads dashboard for current user
  def show
    # gets a list of all of the current user's curricula
    begin
      @created_curricula = Curricula.find_curricula_for_creator current_user
      @contributed_curricula = Curricula.find_curricula_for_contributor current_user
      @followed_curricula = Curricula.find_curricula_for_follower current_user
      check_for_new_commits
    rescue => e
      logger.error e.message
    end

    # get a list of the current user's latest notifications
    @notifications = []
    @created_curricula.each do |c|
      c.notifications.includes(:curricula, :author).find_each do |n|
        @notifications.push(n)
      end
    end

    # gets a list of the off the curricula that a user has contributed to
    @contributed_curricula.each do |c|
      c.curricula.notifications.includes(:curricula, :author).find_each do |n|
        @notifications.push(n)
      end
    end

    # sort notifications by most recent
    @notifications = @notifications.sort_by { |n| n[:created_at] }
    @notifications = @notifications.reverse
  end

  private

  def check_for_new_commits
    @created_curricula.each do |c|
      @git = ::GitFunctionality::Repo.new.get_bare_repo c
      @log = @git.log
      @log.each do |l|
        notification = c.notifications.where('commit_id = ?', l.sha[0..8]).first
        @user = User.find_user_by_email l.author.email
        create_notification_for(0, @user, c, @git.branch.to_s, l) if notification.nil?
      end
    end

    @contributed_curricula.each do |c|
      @git = ::GitFunctionality::Repo.new.get_bare_repo c.curricula
      @log = @git.log
      @log.each do |l|
        notification = c.curricula.notifications.where('commit_id = ?', l.sha[0..8]).first
        @user = User.find_user_by_email l.author.email
        create_notification_for(0, @user, c, @git.branch.to_s, l) if notification.nil?
      end
    end
  end
end

app/views/dashboard/dashboard_main.html.haml
%main
    .col-md-5
        %h2 Notifications:
        %hr

    .col-md-4.col-md-offset-3
        - if !@contributed_curricula.blank?

            .panel.panel-default
                .panel-heading Curricula Contributed To
                .list-group
                    - for c in @contributed_curricula
                        = link_to curricula_path(:id => c.curricula.id) do
                            %h4{:class => 'list-group-item-heading'}= c.curricula.cur_name

        .panel.panel-default
            .panel-heading
                Curricula
                %a{:href => "/curricula/create"}
                    %button.btn.btn-success.btn-sm.pull-right Create Curriculum
            .list-group

                - if @created_curricula.blank?
                    .list-group-item
                        %h4.list-group-item-heading No Curriculum

                - else
                    - for c in @created_curricula
                        =link_to curricula_path(:id => c.id), class: "list-group-item" do
                            %h4.list-group-item-heading= c.cur_name

app/views/dashboard/show.html.erb
<main class="container">
  <div class="col-md-5" title="This is a list of notifications from curricula you own or follow">
    <h2>Notifications:</h2>
    <hr>
    <% @notifications.each do |n| %>
      <%= construct_notification_message_for(n) %>
    <% end %>
  </div>

  <div class="col-md-4 col-md-offset-3" id="contributed-curricula">
    <% if !@contributed_curricula.blank? %>      
      <div class="panel panel-default" title="This is a list of the curricula you are a contributor to">
        <div class="panel-heading" style="padding-bottom: 20px;">
          Curricula Contributed To
        </div>   
        <div class="list-group">
          <% for c in @contributed_curricula %>
            <%= link_to curricula_path(:id => c.curricula.id), class: "list-group-item" do %>
              <h4 class="list-group-item-heading"><%=c.curricula.cur_name%></h4>
            <% end %>
          <% end %>
        </div>            
      </div>
    <% end %>

    <% if !@followed_curricula.blank? %>      
      <div class="panel panel-default" title="This is a list of curricula you follow">
        <div class="panel-heading" style="padding-bottom: 20px;">
          Curricula Following
        </div>   
        <div class="list-group">
          <% for c in @followed_curricula %>
            <%= link_to curricula_path(:id => c.curricula.id), class: "list-group-item" do %>
              <h4 class="list-group-item-heading"><%=c.curricula.cur_name%></h4>
            <% end %>
          <% end %>
        </div>
            
      </div>
    <% end %>

    <div class="panel panel-default" id="created-curricula" title="This is a list of curricula you own">
      <div class="panel-heading" style="padding-bottom: 20px;">
        Curricula
        <%= link_to "Create Curriculum", new_curricula_path, class: "btn btn-success pull-right" %>
      </div>   
      <div class="list-group">

        <% if @created_curricula.blank? %>

          <a class="list-group-item">
              <h4 class="list-group-item-heading">No Curriculum</h4>
          </a>

        <% else %>

          <% for c in @created_curricula %>
            <%= link_to curricula_path(:id => c.id), class: "list-group-item" do %>
              <h4 class="list-group-item-heading"><%= c.cur_name %></h4>
            <% end %>
          <% end %>

        <% end %>

      </div>
    </div>
  </div>
</main>