config/routes.rb
GitMyCurriculum::Application.routes.draw do

  get 'search/uc_search'
  get 'user_root' => 'profile#load'

  authenticated :user do
    root to: 'dashboard#show', as: 'authenticated_root'
  end

  devise_for :users, controllers: { confirmations: 'confirmations', passwords: 'passwords', registrations: 'registrations', sessions: 'sessions' }

  root 'splash#load'

  get 'splash/load'

  get 'profile/edit'
  get 'profile/load'
  get 'dashboard/show'

  resources :curricula do

    member do
      get 'tree/:name' => 'curricula#grab_tree_folder', as: :open_folder
      get 'blob/:name' => 'curricula#grab_file_contents', as: :open_file, :name => /(\w+)(\D+)(\w)/
      get 'fork' => 'curricula#fork', as: :fork
    end

  end

  namespace :curricula do

    get ':id/settings', to: 'settings#show', as: :settings
    post ':id/settings', to: 'settings#show', as: :settings_post

    get 'settings/contributors' => 'settings#update_contributors', as: :contributors
    get 'settings/search' => 'settings#search_results', as: :settings_search

    get ':id/requests/' => 'pull_request#show_requests', as: :requests
    get 'join/:id' => 'pull_request#pull_request', as: :join_request
    get 'merge/:id' => 'pull_request#merge_request', as: :merge
    post 'comment' => 'pull_request#comment', as: :comment

    get ':id/download' => 'exchanges#download', as: :download
    get ':id/upload' => 'exchanges#upload', as: :show_upload
    post ':id/upload' => 'exchanges#upload', as: :post_upload

    get ':id/history' => 'history#show', as: :history
    get ':id/compare/:commit' => 'history#compare', as: :compare
    get ':id/revert/:commit' => 'history#revert', as: :revert

  end

  get 'splash/load'

  get 'subscriptions/subscription'
  post 'subscriptions/subscription' => 'subscriptions#subscription', as: :subscription

  get 'source/show/:id' => 'source#show', as: :source_show
  post 'source/edit' => 'source#edit', as: :source_edit

  get 'featured/show' => 'featured#show', as: :featured_show
  get 'featured/add_featured' => 'featured#add_featured', as: :add_featured
  get 'featured/remove_featured' => 'featured#remove_featured', as: :remove_featured

end

app/controllers/search_controller.rb
# Performs search query based on query strings entered in the search field
# Create instance variable @search set to the return of the query
# Set instance variable @users to the results and render @users in the view
class SearchController < ApplicationController
  # takes in a search string as "query" get param
  # and returns a page of similar users and curricula
  def uc_search
    @all_search = Sunspot.search(User, Curricula) do
      fulltext params[:query] do
        boost_fields username: 2.0
        boost_fields cur_name: 2.0
      end
    end

    @allresults = @all_search.results

    @user_search = User.search do
      fulltext params[:query] do
        boost_fields username: 2.0
      end
    end

    @users = @user_search.results
    @number_of_user_matches = @user_search.total

    @curr_search = Curricula.search do
      fulltext params[:query] do
        boost_fields cur_name: 2.0
      end
    end

    @curricula = @curr_search.results
    @number_of_curriculum_matches = @curr_search.total
  end
end

app/helpers/search_helper.rb
# Helper for search controllers
module SearchHelper
end

app/views/search/_aresult.html.erb
<% for a in @allresults %>
  <% if a.class == User && current_user.username == a.username %>
    <div class="media">
      <% @email = Digest::MD5.hexdigest(a.email.strip.downcase) %>
      <a class="pull-left" href="#">
        <img src="http://www.gravatar.com/avatar/<%= @email %>?s=64px"/>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to(a.username, profile_load_path(:username => a.username)) %>
          <br>
          <%= a.name %>
        </h4>
      </div>
    </div>
    <hr>
  <% elsif a.class == User && current_user.username != a.username %>
    <div class="media">
      <% @email = Digest::MD5.hexdigest(a.email.strip.downcase) %>
      <a class="pull-left" href="#">
        <img src="http://www.gravatar.com/avatar/<%= @email %>?s=64px"/>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to(a.username, profile_load_path(:username => a.username))%>
          <br>
          <%= a.name %>
        </h4>
        <% if current_user && current_user.id!=a.id%>
          
            <% @is_peer = Watching.where('user_id=? AND peer_id=?', current_user.id, a.id) %>
            <% if !@is_peer.blank? %>
            <button class="btn btn-danger btn-no-padding pull-right" >
              <%= link_to "Unfollow", subscriptions_subscription_path(:username => a.username, :query => params[:query], :sub_status => 'user_unfollow', :redirect => 'search'), :class => "no-link-white"  %>
            </button>
            <% else %>
            <button class="btn btn-primary btn-no-padding pull-right" >
              <%= link_to "Follow", subscriptions_subscription_path(:username => a.username, :query => params[:query], :sub_status =>'user_follow', :redirect => 'search'), :class => "no-link-white" %>
            </button>
            <% end %>
          <% end %>
      </div>
    </div>
    <hr>
  <% else %>
    <div class="media">
      <a class="pull-left" href='#'>
        <span class="glyphicon glyphicon-book glyphicon-2x"></span>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <%=link_to("#{a.creator.username}/#{a.cur_name}", curricula_path(:id => a.id))%>
        </h4>
        <%= a.cur_description %>

        <% if current_user && a.creator_id!=current_user.id%>
          <% @followed_curricula = FollowingCurricula.joins(:curricula).where('user_id=? AND curricula_id=?', current_user.id, a.id) %>
            <% if !@followed_curricula.blank? %>
            <button class="btn btn-danger btn-no-padding pull-right" >
              <%= link_to "Unfollow", subscriptions_subscription_path(:cur_id => a.id, :query => params[:query], :sub_status => 'curricula_unfollow', :redirect => 'search'),:class => "no-link-white"  %>
            </button>
            <% else %>
            <button class="btn btn-primary btn-no-padding pull-right" >
              <%= link_to "Follow", subscriptions_subscription_path(:cur_id => a.id, :query => params[:query], :sub_status => 'curricula_follow', :redirect => 'search'), :class => "no-link-white" %>
            </button>
            <% end %>
            
          <% end %>
      </div>
    </div> 
    <hr>
  <% end %>
<% end %>

app/views/search/_cresult.html.erb
<% if @number_of_curriculum_matches == 0 %> 
  <strong> No Matching Curriculums Found</strong>
  <br>
<% else %>
  <% for c in @curricula %>
    <div class="media">
      <a class="pull-left" href='#'>
        <span class="glyphicon glyphicon-book glyphicon-2x"></span>
      </a>

      <div class="media-body">
        <h4 class="media-heading">
          <%=link_to("#{c.creator.username}/#{c.cur_name}", curricula_path(:id => c.id))%>
        </h4>
        <%= c.cur_description %>

        <% if current_user && c.creator_id!=current_user.id%>
          <% @followed_curricula = FollowingCurricula.joins(:curricula).where('user_id=? AND curricula_id=?', current_user.id, c.id) %>
          <% if !@followed_curricula.blank? %>
            <button class="btn btn-danger btn-no-padding pull-right" >
              <%= link_to "Unfollow", subscriptions_subscription_path(:cur_id => c.id, :query => params[:query], :sub_status => 'curricula_unfollow', :redirect => 'search'), :class => "no-link-white" %>
            </button>
          <% else %>
            <button class="btn btn-primary btn-no-padding pull-right" >
              <%= link_to "Follow", subscriptions_subscription_path(:cur_id => c.id, :query => params[:query], :sub_status => 'curricula_follow', :redirect => 'search'), :class => "no-link-white" %>
            </button>
          <% end %>
        <% end %> 
      </div>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/search/_uresult.html.erb
<% if @number_of_user_matches == 0 %>
  <strong> No Matching Users Found</strong> <br>
<% end %>
<% for u in @users %>
  <% if u.class == User && current_user.username == u.username%>
    <div class="media">
      <% @email = Digest::MD5.hexdigest(u.email.strip.downcase) %>
      <a class="pull-left" href="#">
        <img src="http://www.gravatar.com/avatar/<%= @email %>?s=64px"/>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to(u.username, profile_load_path(:username => u.username))%>
          <br>
          <%= u.name %>
        </h4>
      </div>
    </div>
  <hr>
  <% else %>
    <div class="media">
      <% @email = Digest::MD5.hexdigest(u.email.strip.downcase) %>
      <a class="pull-left" href="#">
        <img src="http://www.gravatar.com/avatar/<%= @email %>?s=64px"/>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to(u.username, profile_load_path(:username => u.username))%>
          <br>
          <%= u.name %>
        </h4>
        
          <% if current_user && current_user.id!=u.id%>
          
            <% @is_peer = Watching.where('user_id=? AND peer_id=?', current_user.id, u.id) %>
            <% if !@is_peer.blank? %>
            <button class="btn btn-danger btn-no-padding pull-right" >
              <%= link_to "Unfollow", subscriptions_subscription_path(:username => u.username, :query => params[:query], :sub_status => 'user_unfollow', :redirect => 'search'), :class => "no-link-white"  %>
            </button>
            <% else %>
            <button class="btn btn-primary btn-no-padding pull-right" >
              <%= link_to "Follow", subscriptions_subscription_path(:username => u.username, :query => params[:query], :sub_status =>'user_follow', :redirect => 'search'), :class => "no-link-white" %>
            </button>
            <% end %>
          <% end %>
        
      </div>
    </div>
  <hr>
  <% end %>
<% end %>

app/views/search/uc_search.html.erb
<div class="well well-sm col-md-2 col-md-offset-1 bs-docs-sidebar" title="Select which results you want to see here">

  <ul class="nav nav-pills no-outline nav-stacked">
    <li class="active">
      <a href="#allSearch" data-toggle="tab">
        All Results
        <span class="badge badge-success pull-right">
          <%= @number_of_user_matches + @number_of_curriculum_matches %>
        </span>
      </a>
    </li>
    <li>
      <a href="#userSearch" data-toggle="tab">
        Users
        <span class="badge badge-success pull-right">
          <%= @number_of_user_matches %>
        </span>
      </a>
    </li>
    <li>
      <a href="#currSearch" data-toggle="tab">
        Curriculum
        <span class="badge badge-success pull-right">
          <%= @number_of_curriculum_matches %>
        </span>
      </a>
    </li>
  </ul>
</div>

<div id="Search Results" class="col-md-7">
  <% if @number_of_user_matches==0 && @number_of_curriculum_matches==0 %>
    <h3> No results found for: <%=params[:query]%></h3> <br>
  <% else %>
    <h2>Showing results for: <%=params[:query]%></h2> <br>
    <ul>
      <div id="searchTabContent" class="tab-content">    

        <div class="tab-pane fade in active" id="allSearch">
          <%= render :partial => "aresult" %>
        </div>
        <div class="tab-pane fade" id="userSearch">
          <%= render :partial => "uresult" %>
        </div>
        <div class="tab-pane fade" id="currSearch">
          <%= render :partial => "cresult" %>
        </div>
      </div>
    </ul>
  <% end %>
</div>